name: Publish Package
on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Is this a prerelease.' # use this to control publish tag, for instance NPM wouldn't set latest.
        type: boolean
        required: true
      dry_run:
        description: 'Is this a dry run. If so no package will be published.'
        type: boolean
        required: true

jobs:
  build-publish:
    runs-on: ubuntu-latest
    # Needed to get tokens during publishing.
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - id: build-and-test
        # Build using the same steps from CI.
        name: Build and Test
        uses: ./.github/actions/ci
        env:
          TOOLBAR_INTERNAL_CLIENT_ID: ${{ vars.TOOLBAR_INTERNAL_CLIENT_ID }}
          TOOLBAR_INTERNAL_BASE_URL: ${{ vars.TOOLBAR_INTERNAL_BASE_URL }}
          TOOLBAR_INTERNAL_STREAM_URL: ${{ vars.TOOLBAR_INTERNAL_STREAM_URL }}
          TOOLBAR_INTERNAL_EVENTS_URL: ${{ vars.TOOLBAR_INTERNAL_EVENTS_URL }}

      - uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.2.0
        name: 'Get npm token'
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
          # This gets the npm release token and sets it into the NODE_AUTH_TOKEN environment variable
          ssm_parameter_pairs: '/production/common/releasing/npm/token = NODE_AUTH_TOKEN'

      - id: publish
        name: Publish Package
        uses: ./.github/actions/publish
        with:
          token: ${{ env.NODE_AUTH_TOKEN }}
          prerelease: ${{ inputs.prerelease }}
          dry_run: ${{ inputs.dry_run }}
