name: Run Release Please

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release-package:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        id: release
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Setup Node.js
        if: ${{ fromJson(steps.release.outputs.releases_created) }}
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: '24'

      - name: Install npm
        if: ${{ fromJson(steps.release.outputs.releases_created) }}
        run: npm install -g npm@latest

      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        if: ${{ fromJson(steps.release.outputs.releases_created) }}
        with:
          fetch-depth: 0 # If you only need the current version remove this line.

      - uses: ./.github/actions/ci
        if: ${{ fromJson(steps.release.outputs.releases_created) }}
        env:
          TOOLBAR_INTERNAL_CLIENT_ID: ${{ vars.TOOLBAR_INTERNAL_CLIENT_ID }}
          TOOLBAR_INTERNAL_BASE_URL: ${{ vars.TOOLBAR_INTERNAL_BASE_URL }}
          TOOLBAR_INTERNAL_STREAM_URL: ${{ vars.TOOLBAR_INTERNAL_STREAM_URL }}
          TOOLBAR_INTERNAL_EVENTS_URL: ${{ vars.TOOLBAR_INTERNAL_EVENTS_URL }}

      - uses: ./.github/actions/publish
        if: ${{ fromJson(steps.release.outputs.releases_created) }}
        with:
          prerelease: ${{ contains(steps.release.outputs.tag_name, '-') }}
          dry_run: 'false'
