name: Run Release Please

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  install-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      - run: npm install -g npm@latest

  release-package:
    needs: install-npm
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        id: release
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        if: ${{ fromJson(steps.release.outputs.releases_created) }}
        with:
          fetch-depth: 0 # If you only need the current version remove this line.

      - uses: ./.github/actions/ci
        if: ${{ fromJson(steps.release.outputs.releases_created) }}

      - uses: ./.github/actions/publish
        if: ${{ fromJson(steps.release.outputs.releases_created) }}
        with:
          prerelease: ${{ contains(steps.release.outputs.tag_name, '-') }}
          dry_run: 'false'
